name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '2.7' 
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - name: Build
      run: |
        npm ci
        npm run build
      shell: bash
    - name: Deploy
      run: |
        cd dist
        ln -s index.html 404.html
        git config --global user.email "username@users.noreply.github.com" && git config --global user.name "CD"
        git add -A && git commit -m "Deploy latest"
        git push origin main:dist
      shell: bash