name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '2.7' 
    - uses: actions/setup-node@v3
      with:
        node-version: '14'
    - id: Build
      uses: SubNader/vue-to-github-pages@v1.3.2
      with:
        username: 'SubNader'
        token: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
        source_repository: harran55/vuejs-quran-web
        source_branch: main
        destination_repository: SubNader/ayat
        destination_branch: serve
